version: '3'

services:
  postgis:
    build:
      context: deployments/postgis
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PG_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD:-geoia}
      POSTGRES_USER: ${PG_USER:-geoia}
      POSTGRES_DB: ${PG_DATABASE:-geoia-db}
    volumes:
      - pgdata:/var/lib/postgresql/data

  gdal:
    build:
      context: deployments/gdal
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PG_HOST: postgis
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD:-geoia}
      PG_USER: ${PG_USER:-geoia}
      PG_DATABASE: ${PG_DATABASE:-geoia-db}
    volumes:
      - ./shapefiles:/geoia/data
    depends_on:
      - postgis

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PG_HOST: postgis
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD:-geoia}
      PG_USER: ${PG_USER:-geoia}
      PG_DATABASE: ${PG_DATABASE:-geoia-db}
    ports:
      - ${PORT:-3001}:80
    volumes:
      - ./shapefiles:/usr/src/app/shapefiles
    depends_on:
      - postgis

  backend.dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      PG_HOST: postgis
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD:-geoia}
      PG_USER: ${PG_USER:-geoia}
      PG_DATABASE: ${PG_DATABASE:-geoia-db}
    ports:
      - ${PORT:-3001}:80
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgis

volumes:
  pgdata:
